'use strict';
const $=id=>document.getElementById(id);
const pretty=v=>Number.isInteger(v)?v.toLocaleString():(Math.round(v*10)/10).toLocaleString();
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const date=new Date(),datekey=[date.getFullYear(),date.getMonth()+1,date.getDate()].join('-');
const seed=[...datekey].reduce((a,c)=>Math.imul(a,31)+c.charCodeAt(0)|0,0);
let mini='mix',memoryTimeout=null,wheelState={h:0,s:0,v:1},wheelImage=null,colourGuess=null;
function hexRgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
function rgbHex(rgb){return '#'+rgb.map(c=>Math.round(c).toString(16).padStart(2,'0')).join('').toUpperCase();}
function hsvRgb(h,s,v){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;const r=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return r.map(n=>Math.round((n+m)*255));}
function rgbHsv(rgb){const [r,g,b]=rgb.map(n=>n/255),v=Math.max(r,g,b),lo=Math.min(r,g,b),d=v-lo;let h=d===0?0:v===r?60*((g-b)/d%6):v===g?60*((b-r)/d+2):60*((r-g)/d+4);return {h:(h+360)%360,s:v===0?0:d/v,v};}
function oklab(rgb){const [r,g,b]=rgb.map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;});const l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);return [.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s];}
function colourDistance(a,b){const x=oklab(a),y=oklab(b);return Math.hypot(...x.map((v,i)=>v-y[i]));}
function colourScore(a,b){const d=colourDistance(a,b);return d<=.008?100:Math.round(100*Math.max(0,1-d/.5)**2);}
function makeDeck(random,game=mini){
 const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};

 if(game==='mix')return shuffle(['view3d','balance','motion','perspective','proportion','rhythm','typography','angle','memory','time']).slice(0,5).map(type=>{const puzzles=makeDeck(random,type);return puzzles[Math.floor(random()*puzzles.length)];});

 if(game==='view3d')return Array.from({length:5},(_,i)=>({id:'view-'+i,skill:'3D view',type:'view3d',title:'Match this view.',answer:{yaw:random()*360-180,pitch:random()*120-60,roll:random()*180-90},tip:'Solid is your view. The lime outline is the target.',explain:'Drag turns the shape as if it were a ball under your hand. Drag the outer handle around the ring to tilt the whole view clockwise or counterclockwise. The score measures the smallest rotation between your orientation and the target.'}));
 if(game==='balance')return Array.from({length:5},(_,i)=>{const {points,holes}=makeBalanceShape(random,i);return {id:'balance-'+i,skill:'Balance',type:'balance',title:'Balance it.',points,holes,answer:balanceCentre(points,holes).x,tip:'The lime line marks the centre of mass.',explain:'This is a uniform flat plate. Cutouts remove mass, shifting the balance point away from them. The target is calculated from the filled area, including every notch and hole. A miss tips toward the heavier side. Within 0.5% of the shape’s width earns full points; a 5% miss earns 64 points.'};});
 if(game==='motion')return shuffle([
 [[55,210],[100,35],[290,35],[345,210]],[[55,80],[155,265],[245,35],[345,220]],[[55,220],[130,35],[265,270],[345,80]],[[55,160],[155,60],[255,60],[345,160]],[[55,80],[95,220],[305,220],[345,80]]
 ]).map((control,i)=>{const answer=Array.from({length:81},(_,j)=>{const t=j/80,u=1-t;return {x:u**3*control[0][0]+3*u*u*t*control[1][0]+3*u*t*t*control[2][0]+t**3*control[3][0],y:u**3*control[0][1]+3*u*u*t*control[1][1]+3*u*t*t*control[2][1]+t**3*control[3][1]};});return {id:'trace-'+i,skill:'Line memory',type:'motion',title:'Trace that line.',answer,tip:'Blue is your trace. Lime is the remembered line.',explain:'Remember the shape and position, then draw it in one stroke. Scores compare both paths in both directions, so tracing only a small piece does not earn a high score. Drawing speed and direction do not matter.'};});
 if(game==='perspective')return Array.from({length:5},(_,i)=>({id:'perspective-'+i,skill:'Perspective',type:'perspective',title:'Vanishing point?',answer:{x:100+random()*200,y:70+random()*100},tip:'The lime point is where the receding lines meet.',explain:'These parallel edges recede toward one vanishing point. The dashed extensions reveal their intersection. Scores compare the distance from your point to that intersection.'}));
 if(game==='proportion')return shuffle([['a square',1],['16:9',16/9],['3:2',3/2],['4:3',4/3],['2:1',2]]).map(([label,answer],i)=>({id:'proportion-'+i,skill:'Proportions',type:'proportion',title:'Make '+label+'.',label,answer,tip:'The lime outline shows the target proportion.',explain:'An aspect ratio compares width to height. Any size works: a 16:9 rectangle is about 1.78 times as wide as it is tall. Scores measure ratio error, independently of size.'}));
 if(game==='rhythm')return shuffle([60,72,90,105,120,144]).slice(0,5).map((bpm,i)=>({id:'rhythm-'+i,skill:'Rhythm',type:'rhythm',title:'Copy the pulse.',answer:bpm,tip:'Watch five flashes, then tap five beats at the same pace.',explain:'Your tempo is calculated from the four intervals between your five taps. The score rewards closeness to the target tempo. No sound is played.'}));
 if(game==='typography')return Array.from({length:5},(_,i)=>({id:'type-'+i,skill:'Typography',type:'typography',title:'Recreate it.',word:shuffle(['PLAY','FLOW','BOLD','TYPE','SIZE'])[0],answer:{size:shuffle([36,44,52,60,68])[0],weight:shuffle([400,500,600,700])[0],spacing:shuffle([0,1,2,4])[0]},tip:'Match the size, weight, and spacing.',explain:'Size controls the height of the letters, weight controls stroke thickness, and spacing controls the gaps. All specimens use the same font. Scores compare those three settings.'}));
 if(game==='angle')return shuffle([15,25,35,45,60,75,105,120,135,150,165]).slice(0,5).map((angle,i)=>({id:'angle-'+i,skill:'Angles',type:'angle',title:angle+'°',answer:angle,tip:'Rotate the line. The dashed line marks zero.',explain:'Angles are measured counterclockwise from the right-pointing baseline. A quarter turn is 90° and a half turn is 180°. Scores reward the smallest error in degrees.'}));
 if(game==='memory')return Array.from({length:5},(_,i)=>{const rgb=hsvRgb(random()*360,.35+random()*.6,1);return {id:'memory-'+i,skill:'Colour memory',type:'colour',title:'Find that colour.',answer:rgb,hex:rgbHex(rgb),tip:'Remember the hue and how vivid it is.',explain:'The swatch was visible for two seconds. Hue goes around the wheel; saturation increases towards the edge. The wheel already matches the target brightness.'};});
 if(game==='time')return shuffle([3,5,7,10,12,15]).slice(0,5).map((target,i)=>({id:'time-'+i,skill:'Time awareness',type:'time',title:'Feel '+target+' seconds.',answer:target,unit:' s',tip:'Notice whether you stop early or late.',explain:'The clock measures the interval from Start to Stop. Switching away resets a running round.'}));
 throw new Error('Unknown mini-game');
}
let mode='daily',deck=[],index=0,results=[],locked=false,guess=null,sessionBest=0,review=false,startedAt=null;
function fmt(value,q){return typeof value==='number'?pretty(value)+(q.unit||''):value;}
function scoreFor(value,q){
 const spatial={view3d:()=>[orientationError(value,q.answer),3,180],balance:()=>[Math.abs(value-q.answer)/balanceWidth(q),.005,.25],motion:()=>[traceError(value,q.answer),7,80],perspective:()=>[pointError(value,q.answer),3,250],proportion:()=>[proportionError(value,q.answer),.015,Math.log(2)]};
 if(spatial[q.type]){const [error,tolerance,range]=spatial[q.type]();return error<=tolerance?100:Math.round(100*Math.max(0,1-error/range)**2);}
if(q.type==='rhythm'){const error=Math.abs(Math.log(value/q.answer));return error<=.015?100:Math.round(100*Math.max(0,1-error/Math.log(2))**2);}if(q.type==='angle'){const error=Math.abs(value-q.answer);return error<=1?100:Math.round(100*Math.max(0,1-error/90)**2);}if(q.type==='typography'){const error=(Math.abs(value.size-q.answer.size)/48+Math.abs(value.weight-q.answer.weight)/300+Math.abs(value.spacing-q.answer.spacing)/8)/3;return Math.round(100*Math.max(0,1-error)**2);}if(q.type==='colour')return colourScore(value,q.answer);if(q.type==='time'){const error=Math.abs(value-q.answer);return error<=.05?100:Math.max(0,Math.round(100*Math.max(0,1-error/q.answer)));}return value===q.answer?100:0;}
function timeError(value,q){const delta=value-q.answer;return Math.abs(delta)<=.05?'Right on time':Math.abs(delta).toFixed(2)+' s '+(delta<0?'early':'late');}
function start(nextmode='daily',retryDeck){stopEffects();clearTimeout(memoryTimeout);memoryTimeout=null;mode=nextmode;review=!!retryDeck;deck=retryDeck||makeDeck(rng(mode==='daily'?seed:Math.floor(Math.random()*4294967295)));index=0;results=[];locked=false;guess=null;startedAt=null;$('daily').classList.toggle('active',mode==='daily');$('practice').classList.toggle('active',mode==='practice');$('date').textContent=review?'Another try':mode==='daily'?date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Fresh mix';render();}
function gamebar(){ $('scoremax').textContent='/ '+(deck.length*100); $('roundlabel').textContent='ROUND '+String(Math.min(index+1,deck.length)).padStart(2,'0')+' / '+String(deck.length).padStart(2,'0');$('total').textContent=results.reduce((s,r)=>s+r.score,0).toLocaleString();$('progress').innerHTML=deck.map((_,i)=>`<i class="${i<index?'done':i===index?'current':''}"></i>`).join('');}
function shell(q,content,controls){gamebar();$('playarea').innerHTML=`<div class="mixed-question"><p class="eyebrow">${q.skill}</p><h1 id="challenge">${q.title}</h1>${content}</div><div class="mixed-controls" id="controls">${controls}</div><div class="actionarea" id="actionarea"></div>`;}
function render(){stopEffects();clearTimeout(memoryTimeout);locked=false;guess=null;startedAt=null;const q=deck[index];
 if(q.type==='view3d'){viewRound(q);return;}
 if(q.type==='balance'){balanceRound(q);return;}
 if(q.type==='motion'){motionRound(q);return;}
 if(q.type==='perspective'){perspectiveRound(q);return;}
 if(q.type==='proportion'){proportionRound(q);return;}
 if(q.type==='rhythm'){rhythmRound(q);return;}
 if(q.type==='typography'){typographyRound(q);return;}
 if(q.type==='angle'){angleRound(q);return;}
 if(q.type==='colour'){memoryRound(q);return;}
 if(q.type==='choices'){shell(q,`<div class="cue"><span>${q.caption}</span><strong>${q.cue}</strong></div>`,`<div class="choice-list">${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${escapeHTML(c.label)}</button>`).join('')}</div>`);document.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>reveal(q.choices[Number(btn.dataset.choice)].value)));}
 if(q.type==='time'){shell(q,`<div class="time-cue"><strong>${q.answer}</strong><span>SECONDS</span></div>`,`<button id="timer" class="primary timerbutton">Start</button><p class="small-instruction" id="timerhint">Start. Wait. Stop.</p>`);$('timer').addEventListener('click',()=>{if(startedAt===null){startedAt=performance.now();$('timer').textContent='Stop';$('timer').classList.add('running');$('timerhint').textContent='Trust your internal clock.';$('playarea').querySelector('.time-cue').innerHTML='<strong>· · ·</strong><span>NO PEEKING</span>';}else{const elapsed=(performance.now()-startedAt)/1000;reveal(elapsed);}});}
}

function reveal(value){if(locked)return;stopEffects();clearTimeout(memoryTimeout);locked=true;const q=deck[index],score=scoreFor(value,q);results.push({q,guess:value,score});
 if(q.type==='time'){$('playarea').querySelector('.time-cue').innerHTML=`<strong>${value.toFixed(2)}</strong><span>SECONDS ELAPSED</span>`;}
 $('controls').querySelectorAll('button').forEach(btn=>{btn.disabled=true;if(btn.dataset.choice!==undefined){const c=q.choices[Number(btn.dataset.choice)];btn.classList.toggle('correct',c.value===q.answer);btn.classList.toggle('wrong',c.value===value&&score===0);}});
 gamebar();const feedback=score===100?'Nailed it.':score>=80?'Pretty close.':score>0?'Getting a feel.':'Now you know.';const answerLabel=q.type==='time'?timeError(value,q):q.type==='rhythm'?`Your tempo: ${pretty(value)} BPM · Target: ${q.answer} BPM`:q.type==='angle'?`${Math.abs(value-q.answer).toFixed(1)}° away · Your angle: ${pretty(value)}°`:q.type==='typography'?'Solid: your text · Lime outline: target.':q.type==='colour'?q.hex:q.type==='view3d'?orientationError(value,q.answer).toFixed(1)+'° of rotation away':q.type==='balance'?score===100?'Balanced.': 'Off centre by '+(Math.abs(value-q.answer)/balanceWidth(q)*100).toFixed(1)+'% of the shape’s width':q.type==='motion'?'Average line error: '+Math.round(traceError(value,q.answer))+' units':q.type==='perspective'?Math.round(pointError(value,q.answer))+' units away':q.type==='proportion'?'Your ratio: '+(value.width/value.height).toFixed(2)+' : 1 · Target: '+q.label:q.answer;
 if(q.type==='balance'){const tilt=score===100?0:Math.sign(q.answer-value)*18;for(let i=0;i<=15;i++)afterEffect(()=>drawBalance(q,value,tilt*i/15,true),i*20);}
 if(q.type==='view3d'){drawShape3D($('view-canvas'),value);drawShape3D($('view-canvas'),q.answer,{overlay:true});$('view-canvas').setAttribute('aria-label','Your 3D view with the target overlaid as a lime outline.');$('view-hint').textContent='Solid: your view · Lime outline: target.';}
 if(q.type==='motion')drawTrace(value,q.answer);
 if(q.type==='perspective')drawPerspective(q,value,true);
 if(q.type==='proportion')drawProportion(value,q.answer);
 document.querySelectorAll('.spatial-input').forEach(el=>el.disabled=true);
 if(q.type==='angle')drawAngle(value,q.answer);
 if(q.type==='typography'){document.querySelectorAll('.type-slider').forEach(el=>el.disabled=true);$('type-preview').classList.add('type-overlay');$('type-preview').innerHTML=typeHTML(q.word,value).replace('class="type-word"','class="type-word type-overlay-guess"')+typeHTML(q.word,q.answer).replace('class="type-word"','class="type-word type-overlay-target"');$('type-preview').setAttribute('aria-label','Your text with the target overlaid as a lime outline.');}
 if(q.type==='colour'){document.querySelectorAll('.colour-input').forEach(el=>el.disabled=true);$('wheel').setAttribute('aria-disabled','true');drawWheel(q.answer);}

 $('actionarea').innerHTML=`<div class="feedback" aria-live="polite"><div class="feedbacktop"><h2>${feedback}</h2><span class="points">+${score.toLocaleString()} pts</span></div><div class="colour-comparison">${q.type==='colour'?`<div><div class="compare-swatch" style="background:${rgbHex(value)}"></div><span>Your guess</span><small>${rgbHex(value)}</small></div><div><div class="compare-swatch" style="background:${q.hex}"></div><span>Target</span><small>${q.hex}</small></div>`:`<p class="answertext">${escapeHTML(answerLabel)}</p>`}</div><p class="quick-tip">${q.type==='time'?'Target: '+q.answer+' s':q.tip}</p><details class="math-detail"><summary>Why it works</summary><p class="lesson">${q.explain}${q.source?` <a href="${q.source[1]}" target="_blank" rel="noopener">${q.source[0]}</a>`:''}</p></details><button id="next" class="primary">${index+1===deck.length?'See my results':'Next round'}</button></div>`;$('next').addEventListener('click',()=>{index++;if(index===deck.length)finish();else render();});$('next').focus({preventScroll:true});}
function finish(){gamebar();const total=results.reduce((s,r)=>s+r.score,0),max=deck.length*100;sessionBest=Math.max(sessionBest,total/max);$('roundlabel').textContent='MIX COMPLETE';$('progress').innerHTML=deck.map(()=>'<i class="done"></i>').join('');$('playarea').innerHTML=`<div class="summary"><p class="eyebrow">${mode==='daily'&&!review?'DAILY MIX':'PRACTICE'} · COMPLETE</p><h1>A little sharper.</h1><div class="bigscore">${total.toLocaleString()}<small> / ${max.toLocaleString()}</small></div><p class="summary-intro">${review?"Another pass at your toughest rounds.":"Five rounds. A little better feel."}</p><div class="results">${results.map(r=>`<div class="result"><div class="resulthead"><span>${r.q.type==='time'?'Feel '+r.q.answer+' seconds':r.q.type==='colour'?r.q.skill+(r.q.source?' · '+r.q.title:''):r.q.cue||r.q.skill}</span><span>${r.score} pts</span></div><p>${r.q.type==='time'?r.q.answer+' s target · '+timeError(r.guess,r.q):r.q.type==='colour'?'Your guess '+rgbHex(r.guess)+' · Target '+r.q.hex:r.q.tip}</p></div>`).join('')}</div><div class="summary-actions"><button id="again" class="primary">Play a fresh mix</button><button id="retry" class="secondary">Retry my toughest three</button></div><p class="tiny">Best score this session: ${Math.round(sessionBest*100)}% · Daily mix follows your device’s date.</p></div>`;$('again').addEventListener('click',()=>start('practice'));$('retry').addEventListener('click',()=>start('practice',results.slice().sort((a,b)=>a.score-b.score).slice(0,3).map(r=>r.q)));}
function memoryRound(q){shell(q,`<div class="memory-stage" id="memory-stage"><span class="memory-prompt">Two seconds to remember it.</span></div>`,`<button class="primary" id="show-colour">Show colour</button>`);$('show-colour').addEventListener('click',()=>{$('show-colour').disabled=true;$('show-colour').textContent='Remember it…';$('memory-stage').style.background=q.hex;$('memory-stage').innerHTML='';memoryTimeout=setTimeout(()=>{memoryTimeout=null;colourPicker(q);},2000);});}
function colourPicker(q){wheelState={h:0,s:0,v:q.source?rgbHsv(q.answer).v:1};colourGuess=null;wheelImage=null;shell(q,`<p class="colour-caption">${q.source?q.caption:'From memory.'}</p>`,`<div class="wheel-wrap"><canvas width="480" height="480" id="wheel" tabindex="0" role="application" aria-label="Colour wheel. Left and right change hue; up and down change saturation."></canvas></div><div class="colour-adjust"><span>Your colour</span><span class="chosen-swatch" id="chosen" aria-label="Your selected colour"></span></div><details class="keyboard-colour"><summary>Keyboard controls</summary><label for="hue">Hue</label><input class="colour-input" id="hue" type="range" min="0" max="359" value="0"><label for="saturation">Saturation</label><input class="colour-input" id="saturation" type="range" min="0" max="100" value="0"></details><button class="primary" id="colour-lock" disabled>Pick a colour</button>`);
 const choose=()=>{colourGuess=hsvRgb(wheelState.h,wheelState.s,wheelState.v);$('chosen').style.background=rgbHex(colourGuess);$('chosen').setAttribute('aria-label','Your selected colour');$('colour-lock').disabled=false;$('colour-lock').textContent='Lock it in';$('hue').value=Math.round(wheelState.h);$('saturation').value=Math.round(wheelState.s*100);drawWheel();};
 const wheel=$('wheel');const point=e=>{if(locked)return;const rect=wheel.getBoundingClientRect(),dx=(e.clientX-rect.left)/rect.width*480-240,dy=(e.clientY-rect.top)/rect.height*480-240;wheelState.h=(Math.atan2(dy,dx)*180/Math.PI+360)%360;wheelState.s=Math.min(1,Math.hypot(dx,dy)/230);choose();};let dragging=false;wheel.addEventListener('pointerdown',e=>{e.preventDefault();dragging=true;wheel.setPointerCapture(e.pointerId);point(e);});wheel.addEventListener('pointermove',e=>{if(dragging)point(e);});wheel.addEventListener('pointerup',()=>dragging=false);wheel.addEventListener('pointercancel',()=>dragging=false);
 wheel.addEventListener('keydown',e=>{if(locked)return;const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'];if(!keys.includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')wheelState.h=(wheelState.h+357)%360;if(e.key==='ArrowRight')wheelState.h=(wheelState.h+3)%360;if(e.key==='ArrowUp')wheelState.s=Math.min(1,wheelState.s+.02);if(e.key==='ArrowDown')wheelState.s=Math.max(0,wheelState.s-.02);choose();});
 $('hue').addEventListener('input',()=>{wheelState.h=Number($('hue').value);choose();});$('saturation').addEventListener('input',()=>{wheelState.s=Number($('saturation').value)/100;choose();});$('colour-lock').addEventListener('click',()=>{if(colourGuess)reveal(colourGuess);});drawWheel();
}
function drawWheel(target){const canvas=$('wheel');if(!canvas)return;const ctx=canvas.getContext('2d');if(!wheelImage){wheelImage=ctx.createImageData(480,480);for(let y=0;y<480;y++)for(let x=0;x<480;x++){const dx=x-240,dy=y-240,d=Math.hypot(dx,dy);if(d>230)continue;const h=(Math.atan2(dy,dx)*180/Math.PI+360)%360,rgb=hsvRgb(h,d/230,wheelState.v),i=(y*480+x)*4;wheelImage.data.set([...rgb,255],i);}}ctx.clearRect(0,0,480,480);ctx.putImageData(wheelImage,0,0);
 const mark=(state,style)=>{const angle=state.h*Math.PI/180,x=240+Math.cos(angle)*state.s*230,y=240+Math.sin(angle)*state.s*230;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.strokeStyle='#17234d';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle=style;ctx.lineWidth=3;ctx.stroke();};if(colourGuess)mark(wheelState,'white');if(target){mark(rgbHsv(target),'#e5ff57');}}
let effectTimers=[],effectEpoch=0,rhythmActive=false;
function stopEffects(){effectEpoch++;effectTimers.forEach(clearTimeout);effectTimers=[];rhythmActive=false;}
function afterEffect(fn,delay){const epoch=effectEpoch;const id=setTimeout(()=>{effectTimers=effectTimers.filter(t=>t!==id);if(epoch===effectEpoch)fn();},delay);effectTimers.push(id);}
function rhythmRound(q){shell(q,`<div class="pulse-stage"><div class="pulse" id="pulse"></div><span id="pulse-label">Watch. Then tap.</span><div class="beat-count" id="beat-count">○ ○ ○ ○ ○</div></div>`,`<button class="primary" id="rhythm-action">Watch pulse</button>`);let stage='ready',taps=[];const button=$('rhythm-action');
 const flash=()=>{$('pulse').classList.add('lit');afterEffect(()=>$('pulse')?.classList.remove('lit'),120);};
 button.addEventListener('click',()=>{if(locked)return;if(stage==='ready'){stage='watching';rhythmActive=true;button.disabled=true;button.textContent='Watch…';$('pulse-label').textContent='Remember the pace.';for(let i=0;i<5;i++)afterEffect(()=>{flash();$('beat-count').textContent=Array.from({length:5},(_,j)=>j<=i?'●':'○').join(' ');},i*60000/q.answer);afterEffect(()=>{stage='tapping';button.disabled=false;button.textContent='Tap';$('pulse-label').textContent='Your turn. Five taps.';$('beat-count').textContent='○ ○ ○ ○ ○';button.focus({preventScroll:true});},4*60000/q.answer+500);}else if(stage==='tapping'){taps.push(performance.now());flash();$('beat-count').textContent=Array.from({length:5},(_,j)=>j<taps.length?'●':'○').join(' ');if(taps.length===5){stage='done';rhythmActive=false;reveal(60000/((taps[4]-taps[0])/4));}}});}
function typeHTML(word,settings){return `<span class="type-word" style="font-size:${settings.size}px;font-weight:${settings.weight};letter-spacing:${settings.spacing}px">${word}</span>`;}
function typographyRound(q){shell(q,`<div class="type-specimen" id="type-preview"><span class="memory-prompt">Two seconds to remember it.</span></div>`,`<button class="primary" id="show-type">Show type</button>`);$('show-type').addEventListener('click',()=>{$('show-type').disabled=true;$('show-type').textContent='Remember it…';$('type-preview').innerHTML=typeHTML(q.word,q.answer);afterEffect(()=>typographyPicker(q),2000);});}
function typographyPicker(q){let settings={size:52,weight:400,spacing:0};shell(q,`<div class="type-specimen" id="type-preview">${typeHTML(q.word,settings)}</div>`,`<div class="type-sliders"><label for="type-size">Size</label><input class="type-slider" id="type-size" type="range" min="28" max="76" value="52"><label for="type-weight">Weight</label><input class="type-slider" id="type-weight" type="range" min="400" max="700" step="100" value="400"><label for="type-spacing">Spacing</label><input class="type-slider" id="type-spacing" type="range" min="-2" max="6" step="0.25" value="0"></div><button class="primary" id="type-lock">Lock it in</button>`);['size','weight','spacing'].forEach(key=>$('type-'+key).addEventListener('input',()=>{settings[key]=Number($('type-'+key).value);$('type-preview').innerHTML=typeHTML(q.word,settings);}));$('type-lock').addEventListener('click',()=>reveal({...settings}));}
function angleRound(q){let angle=90,chosen=false;shell(q,`<div class="angle-wrap"><canvas width="400" height="260" id="angle-dial" tabindex="0" role="application" aria-label="Rotate the line to ${q.answer} degrees. Left and right arrows adjust it."></canvas></div>`,`<p class="small-instruction">Drag the line or use arrow keys.</p><button class="primary" id="angle-lock" disabled>Choose your angle</button>`);const dial=$('angle-dial');const choose=v=>{if(locked)return;angle=Math.max(0,Math.min(180,v));chosen=true;drawAngle(angle);$('angle-lock').disabled=false;$('angle-lock').textContent='Lock it in';};const point=e=>{const rect=dial.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*400-200,y=220-(e.clientY-rect.top)/rect.height*260;choose(Math.atan2(Math.max(0,y),x)*180/Math.PI);};let drag=false;dial.addEventListener('pointerdown',e=>{e.preventDefault();drag=true;dial.setPointerCapture(e.pointerId);point(e);});dial.addEventListener('pointermove',e=>{if(drag)point(e);});dial.addEventListener('pointerup',()=>drag=false);dial.addEventListener('pointercancel',()=>drag=false);dial.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();choose(angle+(e.key==='ArrowLeft'?1:-1));}});$('angle-lock').addEventListener('click',()=>{if(chosen)reveal(angle);});drawAngle(angle);}
function drawAngle(angle,target){const canvas=$('angle-dial');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,400,260);ctx.strokeStyle='#cbd5ed';ctx.lineWidth=2;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(200,220);ctx.lineTo(375,220);ctx.stroke();ctx.setLineDash([]);const line=(a,colour,width)=>{const t=a*Math.PI/180;ctx.beginPath();ctx.moveTo(200,220);ctx.lineTo(200+Math.cos(t)*155,220-Math.sin(t)*155);ctx.strokeStyle=colour;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke();};if(target!==undefined)line(target,'#a4be21',5);line(angle,'#2448ed',5);ctx.fillStyle='#17234d';ctx.beginPath();ctx.arc(200,220,7,0,Math.PI*2);ctx.fill();}
function rotationMatrix(o){if(o.matrix)return o.matrix;const x=o.pitch*Math.PI/180,y=o.yaw*Math.PI/180,z=o.roll*Math.PI/180,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);return [cz*cy,cz*sy*sx-sz*cx,cz*sy*cx+sz*sx,sz*cy,sz*sy*sx+cz*cx,sz*sy*cx-cz*sx,-sy,cy*sx,cy*cx];}
function orientationError(a,b){const x=rotationMatrix(a),y=rotationMatrix(b),trace=x.reduce((n,v,i)=>n+v*y[i],0);return Math.acos(Math.max(-1,Math.min(1,(trace-1)/2)))*180/Math.PI;}
function polygonCentre(points){let crossSum=0,xsum=0,ysum=0;for(let i=0;i<points.length;i++){const [x,y]=points[i],[u,v]=points[(i+1)%points.length],c=x*v-u*y;crossSum+=c;xsum+=(x+u)*c;ysum+=(y+v)*c;}return {x:xsum/(3*crossSum),y:ysum/(3*crossSum)};}
function resampleTrace(points,count=80){if(points.length<2)return points;const lengths=[0];for(let i=1;i<points.length;i++)lengths.push(lengths[i-1]+pointError(points[i],points[i-1]));const total=lengths[lengths.length-1];if(total===0)return [points[0]];let segment=1;return Array.from({length:count},(_,i)=>{const distance=total*i/(count-1);while(segment<points.length-1&&lengths[segment]<distance)segment++;const span=lengths[segment]-lengths[segment-1],t=span?(distance-lengths[segment-1])/span:0,a=points[segment-1],b=points[segment];return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};});}
function traceError(a,b){if(a.length<2)return 400;const x=resampleTrace(a),y=resampleTrace(b);const average=(from,to)=>from.reduce((sum,p)=>sum+Math.min(...to.map(q=>pointError(p,q))),0)/from.length;return (average(x,y)+average(y,x))/2;}
function pointError(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function proportionError(a,b){return Math.abs(Math.log((a.width/a.height)/b));}
function spatialCanvas(q,id,controls=''){shell(q,`<div class="spatial-wrap"><canvas id="${id}" width="400" height="300" tabindex="0" role="application" aria-label="${q.title}"></canvas></div>`,controls);}
function attachPointInput(canvas,fn){let drag=false;const point=e=>{if(locked)return;const r=canvas.getBoundingClientRect();fn({x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height});};canvas.addEventListener('pointerdown',e=>{e.preventDefault();drag=true;canvas.setPointerCapture(e.pointerId);point(e);});canvas.addEventListener('pointermove',e=>{if(drag)point(e);});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);}
function drawShape3D(canvas,orientation,options={}){if(!canvas)return;const ctx=canvas.getContext('2d'),r=rotationMatrix(orientation),rotate=p=>[r[0]*p[0]+r[1]*p[1]+r[2]*p[2],r[3]*p[0]+r[4]*p[1]+r[5]*p[2],r[6]*p[0]+r[7]*p[1]+r[8]*p[2]],faces=[];const boxes=[[-.3,0,0,1.5,.65,.6,'#2448ED'],[.5,.56,0,.5,.47,.6,'#D4EE46'],[-.6,-.1,.55,.5,.45,.5,'#F08A55']];for(const [x,y,z,w,h,d,hex]of boxes){const vertices=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(([a,b,c])=>rotate([x+a*w/2,y+b*h/2,z+c*d/2]));for(const ids of [[0,1,2,3],[4,5,6,7],[0,4,7,3],[1,5,6,2],[3,2,6,7],[0,1,5,4]]){const points=ids.map(i=>vertices[i]),depth=points.reduce((s,p)=>s+p[2],0)/4,edge1=points[1].map((v,i)=>v-points[0][i]),edge2=points[2].map((v,i)=>v-points[0][i]),normal=[edge1[1]*edge2[2]-edge1[2]*edge2[1],edge1[2]*edge2[0]-edge1[0]*edge2[2],edge1[0]*edge2[1]-edge1[1]*edge2[0]],shade=.68+.3*Math.abs(normal[2])/Math.hypot(...normal);faces.push({points,depth,colour:rgbHex(hexRgb(hex).map(v=>v*shade))});}}
 ctx.save();if(!options.overlay){ctx.clearRect(0,0,400,300);ctx.fillStyle='#f3f6ff';ctx.fillRect(0,0,400,300);}for(const face of faces.sort((a,b)=>a.depth-b.depth)){const pts=face.points.map(([x,y,z])=>[200+x*90*4/(4-z),155-y*90*4/(4-z)]);ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=options.overlay?'#d4ee46':face.colour;ctx.globalAlpha=options.overlay?.12:1;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=options.overlay?'#8ba715':'#17234d44';ctx.lineWidth=options.overlay?2:1;ctx.stroke();}ctx.restore();}
function viewRound(q){spatialCanvas(q,'view-canvas','<button id="show-view" class="primary">Show view</button>');$('view-canvas').setAttribute('aria-label','3D view preview');drawShape3D($('view-canvas'),{yaw:0,pitch:0,roll:0});$('show-view').addEventListener('click',()=>{$('show-view').disabled=true;$('show-view').textContent='Remember it…';drawShape3D($('view-canvas'),q.answer);afterEffect(()=>viewPicker(q),3000);});}
function multiplyRotation(a,b){return Array.from({length:9},(_,i)=>{const row=Math.floor(i/3),col=i%3;return a[row*3]*b[col]+a[row*3+1]*b[col+3]+a[row*3+2]*b[col+6];});}
function axisRotation(axis,angle){const length=Math.hypot(...axis);if(length<1e-10)return rotationMatrix({yaw:0,pitch:0,roll:0});const [x,y,z]=axis.map(v=>v/length),c=Math.cos(angle),s=Math.sin(angle),t=1-c;return [t*x*x+c,t*x*y-s*z,t*x*z+s*y,t*x*y+s*z,t*y*y+c,t*y*z-s*x,t*x*z-s*y,t*y*z+s*x,t*z*z+c];}
function ballPoint(p){let x=(p.x-200)/110,y=(155-p.y)/110;const length=Math.hypot(x,y);if(length>1){x/=length;y/=length;return [x,y,0];}return [x,y,Math.sqrt(1-x*x-y*y)];}
function ballRotation(from,to){const a=ballPoint(from),b=ballPoint(to),axis=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=Math.max(-1,Math.min(1,a.reduce((s,v,i)=>s+v*b[i],0)));if(dot<-.999999&&Math.hypot(...axis)<1e-8)return axisRotation(Math.abs(a[0])<.9?[0,-a[2],a[1]]:[-a[1],a[0],0],Math.PI);return axisRotation(axis,Math.acos(dot));}
function drawViewControls(canvas,angle){const ctx=canvas.getContext('2d');ctx.beginPath();ctx.arc(200,155,132,0,Math.PI*2);ctx.strokeStyle='#ccd6ee';ctx.lineWidth=2;ctx.setLineDash([3,6]);ctx.stroke();ctx.setLineDash([]);const x=200+Math.cos(angle)*132,y=155+Math.sin(angle)*132;ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fillStyle='#e5ff57';ctx.fill();ctx.strokeStyle='#17234d';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#17234d';ctx.font='17px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('↻',x,y);}
function viewPicker(q){let orientation={matrix:rotationMatrix({yaw:0,pitch:0,roll:0})},twist=-Math.PI/4;spatialCanvas(q,'view-canvas','<p id="view-hint" class="small-instruction">Drag the shape to turn it. Drag the green handle around the ring to tilt.</p><button id="view-lock" class="primary">Lock it in</button>');const canvas=$('view-canvas');canvas.setAttribute('aria-label','Drag the shape to rotate. Drag the outer ring to tilt clockwise or counterclockwise. Arrow keys turn; Shift plus left or right tilts.');const redraw=()=>{drawShape3D(canvas,orientation);drawViewControls(canvas,twist);};const point=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*400,y:(e.clientY-r.top)/r.height*300};};let drag=false,prev=null,tilting=false;canvas.addEventListener('pointerdown',e=>{if(locked)return;e.preventDefault();drag=true;prev=point(e);tilting=Math.hypot(prev.x-200,prev.y-155)>117;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||locked)return;const next=point(e);let change;if(tilting){const a=Math.atan2(prev.y-155,prev.x-200),b=Math.atan2(next.y-155,next.x-200),delta=Math.atan2(Math.sin(b-a),Math.cos(b-a));twist+=delta;change=axisRotation([0,0,1],-delta);}else change=ballRotation(prev,next);orientation={matrix:multiplyRotation(change,orientation.matrix)};prev=next;redraw();});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('keydown',e=>{if(locked||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const amount=3*Math.PI/180;let change;if(e.shiftKey&&['ArrowLeft','ArrowRight'].includes(e.key)){const delta=e.key==='ArrowRight'?amount:-amount;twist+=delta;change=axisRotation([0,0,1],-delta);}else change=axisRotation(['ArrowLeft','ArrowRight'].includes(e.key)?[0,1,0]:[1,0,0],['ArrowLeft','ArrowUp'].includes(e.key)?-amount:amount);orientation={matrix:multiplyRotation(change,orientation.matrix)};redraw();});$('view-lock').addEventListener('click',()=>reveal({matrix:orientation.matrix.slice()}));redraw();}
function polygonArea(points){let area=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];area+=a[0]*b[1]-b[0]*a[1];}return Math.abs(area)/2;}
function balanceCentre(points,holes=[]){let area=polygonArea(points),centre=polygonCentre(points),x=centre.x*area,y=centre.y*area;for(const hole of holes){const removed=polygonArea(hole),c=polygonCentre(hole);area-=removed;x-=removed*c.x;y-=removed*c.y;}return {x:x/area,y:y/area};}
function makeBalanceShape(random,round){const count=5+round%3,weights=Array.from({length:count},()=>.6+random()),sum=weights.reduce((a,b)=>a+b),xs=[45];weights.forEach(w=>xs.push(xs[xs.length-1]+310*w/sum));const tops=Array.from({length:count},()=>45+random()*100),points=[],holes=[];for(let i=0;i<count;i++){points.push([xs[i],tops[i]],[xs[i+1],tops[i]]);}points.push([355,190],[45,190]);const candidates=tops.map((top,i)=>({top,i})).sort((a,b)=>a.top-b.top);for(const {top,i}of candidates.slice(0,2+round%2)){const width=xs[i+1]-xs[i],cx=(xs[i]+xs[i+1])/2,cy=top+(190-top)*.48,rx=width*(.24+random()*.1),ry=(190-top)*(.2+random()*.08);if(round%2===0)holes.push(Array.from({length:24},(_,j)=>{const t=j/24*Math.PI*2;return [cx+Math.cos(t)*rx,cy+Math.sin(t)*ry];}));else holes.push([[cx-rx,cy-ry],[cx+rx,cy-ry],[cx+rx,cy+ry],[cx-rx,cy+ry]]);}return {points,holes};}
function balanceWidth(q){const xs=q.points.map(p=>p[0]);return Math.max(...xs)-Math.min(...xs);}
function balanceRound(q){let support=200;spatialCanvas(q,'balance-canvas','<p class="small-instruction">Move the support. The cutouts contain no material.</p><button id="balance-lock" class="primary">Test the balance</button>');attachPointInput($('balance-canvas'),p=>{support=Math.max(35,Math.min(365,p.x));drawBalance(q,support);});$('balance-canvas').addEventListener('keydown',e=>{if(locked||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();support=Math.max(35,Math.min(365,support+(e.key==='ArrowLeft'?-1:1)));drawBalance(q,support);});$('balance-lock').addEventListener('click',()=>reveal(support));drawBalance(q,support);}
function drawBalance(q,support,tilt=0,showTarget=false){const canvas=$('balance-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,400,300);if(showTarget){ctx.strokeStyle='#a4be21';ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(q.answer,45);ctx.lineTo(q.answer,230);ctx.stroke();ctx.setLineDash([]);}ctx.save();ctx.translate(support,190);ctx.rotate(tilt*Math.PI/180);ctx.translate(-support,-190);ctx.beginPath();q.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();for(const hole of q.holes||[]){hole.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}ctx.fillStyle='#2448ed';ctx.fill('evenodd');ctx.strokeStyle='#17234d';ctx.lineWidth=1;ctx.stroke();ctx.restore();ctx.beginPath();ctx.moveTo(support,193);ctx.lineTo(support-15,221);ctx.lineTo(support+15,221);ctx.closePath();ctx.fillStyle='#e5ff57';ctx.fill();ctx.strokeStyle='#9cab2c';ctx.stroke();ctx.strokeStyle='#cad4ed';ctx.beginPath();ctx.moveTo(25,223);ctx.lineTo(375,223);ctx.stroke();}
function motionRound(q){spatialCanvas(q,'trace-canvas','<p class="small-instruction">Two seconds to remember it.</p><button id="show-line" class="primary">Show line</button>');drawTrace([]);$('show-line').addEventListener('click',()=>{$('show-line').disabled=true;$('show-line').textContent='Remember it…';drawTrace(q.answer);afterEffect(()=>tracePicker(q),2000);});}
function tracePicker(q){let points=[],drawing=false,cursor={x:200,y:150};spatialCanvas(q,'trace-canvas','<p class="small-instruction">Draw the line in one stroke.</p><div class="preview-actions"><button id="clear-trace" class="secondary">Clear</button><button id="trace-lock" class="primary" disabled>Lock it in</button></div>');const canvas=$('trace-canvas');canvas.setAttribute('aria-label','Draw the remembered line. Keyboard: arrows move, Space adds a point.');const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(400,(e.clientX-r.left)/r.width*400)),y:Math.max(0,Math.min(300,(e.clientY-r.top)/r.height*300))};};const update=()=>{drawTrace(points);$('trace-lock').disabled=points.length<2||pointError(points[0],points[points.length-1])<10;};canvas.addEventListener('pointerdown',e=>{if(locked)return;e.preventDefault();drawing=true;canvas.setPointerCapture(e.pointerId);points=[point(e)];update();});canvas.addEventListener('pointermove',e=>{if(!drawing||locked)return;const p=point(e);if(pointError(p,points[points.length-1])>=1){points.push(p);update();}});canvas.addEventListener('pointerup',e=>{if(!drawing||locked)return;points.push(point(e));drawing=false;update();});canvas.addEventListener('pointercancel',()=>drawing=false);canvas.addEventListener('keydown',e=>{if(locked||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')cursor.x=Math.max(0,cursor.x-5);if(e.key==='ArrowRight')cursor.x=Math.min(400,cursor.x+5);if(e.key==='ArrowUp')cursor.y=Math.max(0,cursor.y-5);if(e.key==='ArrowDown')cursor.y=Math.min(300,cursor.y+5);if(e.key===' ')points.push({...cursor});update();const ctx=canvas.getContext('2d');ctx.strokeStyle='#17234d';ctx.strokeRect(cursor.x-4,cursor.y-4,8,8);});$('clear-trace').addEventListener('click',()=>{points=[];update();});$('trace-lock').addEventListener('click',()=>{if(!$('trace-lock').disabled)reveal(points.map(p=>({...p})));});drawTrace([]);}
function drawTrace(points,target){const canvas=$('trace-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,400,300);ctx.fillStyle='#f3f6ff';ctx.fillRect(0,0,400,300);const path=(list,colour)=>{if(!list.length)return;ctx.beginPath();list.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=colour;ctx.stroke();};if(target)path(target,'#a4be21');path(points,'#2448ed');}
function perspectiveRound(q){let point=null;spatialCanvas(q,'perspective-canvas','<p class="small-instruction">Tap where the receding lines would meet.</p><button id="perspective-lock" class="primary" disabled>Place your point</button>');attachPointInput($('perspective-canvas'),p=>{point={x:Math.max(0,Math.min(400,p.x)),y:Math.max(0,Math.min(300,p.y))};drawPerspective(q,point);$('perspective-lock').disabled=false;$('perspective-lock').textContent='Lock it in';});$('perspective-canvas').addEventListener('keydown',e=>{if(locked||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();point=point||{x:200,y:150};if(e.key==='ArrowLeft')point.x=Math.max(0,point.x-3);if(e.key==='ArrowRight')point.x=Math.min(400,point.x+3);if(e.key==='ArrowUp')point.y=Math.max(0,point.y-3);if(e.key==='ArrowDown')point.y=Math.min(300,point.y+3);drawPerspective(q,point);$('perspective-lock').disabled=false;$('perspective-lock').textContent='Lock it in';});$('perspective-lock').addEventListener('click',()=>{if(point)reveal({...point});});drawPerspective(q);}
function drawPerspective(q,point,revealTarget=false){const canvas=$('perspective-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),vp=q.answer,corners=[[20,20],[380,20],[380,280],[20,280]],towards=([x,y],scale)=>[vp.x+(x-vp.x)*scale,vp.y+(y-vp.y)*scale];ctx.clearRect(0,0,400,300);ctx.fillStyle='#f3f6ff';ctx.fillRect(0,0,400,300);ctx.strokeStyle='#7c91be';ctx.lineWidth=1.5;for(const c of corners){const end=towards(c,.65);ctx.beginPath();ctx.moveTo(...c);ctx.lineTo(...end);ctx.stroke();}for(const scale of [1,.83,.65]){ctx.beginPath();corners.map(c=>towards(c,scale)).forEach((c,i)=>i?ctx.lineTo(...c):ctx.moveTo(...c));ctx.closePath();ctx.stroke();}const mark=(p,colour)=>{ctx.fillStyle=colour;ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#17234d';ctx.lineWidth=2;ctx.stroke();};if(revealTarget){ctx.setLineDash([3,5]);ctx.strokeStyle='#b3c72e';for(const c of corners){ctx.beginPath();ctx.moveTo(...towards(c,.65));ctx.lineTo(vp.x,vp.y);ctx.stroke();}ctx.setLineDash([]);mark(vp,'#e5ff57');}if(point)mark(point,'#2448ed');}
function proportionRound(q){let size={width:170,height:140};spatialCanvas(q,'proportion-canvas','<p class="small-instruction">Drag the corner. Arrow keys change width and height.</p><button id="proportion-lock" class="primary">Lock it in</button>');const canvas=$('proportion-canvas');attachPointInput(canvas,p=>{size.width=Math.max(40,Math.min(320,p.x-40));size.height=Math.max(40,Math.min(230,p.y-35));drawProportion(size);});canvas.addEventListener('keydown',e=>{if(locked||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')size.width=Math.max(40,size.width-3);if(e.key==='ArrowRight')size.width=Math.min(320,size.width+3);if(e.key==='ArrowUp')size.height=Math.max(40,size.height-3);if(e.key==='ArrowDown')size.height=Math.min(230,size.height+3);drawProportion(size);});$('proportion-lock').addEventListener('click',()=>reveal({...size}));drawProportion(size);}
function drawProportion(size,target){const canvas=$('proportion-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,400,300);ctx.fillStyle='#2448ed12';ctx.fillRect(40,35,size.width,size.height);ctx.strokeStyle='#2448ed';ctx.lineWidth=3;ctx.strokeRect(40,35,size.width,size.height);if(target!==undefined){const h=Math.min(size.height,320/target);ctx.strokeStyle='#a4be21';ctx.setLineDash([5,5]);ctx.strokeRect(40,35,h*target,h);ctx.setLineDash([]);}ctx.fillStyle='#e5ff57';ctx.fillRect(40+size.width-7,35+size.height-7,14,14);ctx.strokeStyle='#17234d';ctx.lineWidth=1;ctx.strokeRect(40+size.width-7,35+size.height-7,14,14);}

document.addEventListener('visibilitychange',()=>{if(document.hidden&&(rhythmActive||(!locked&&['typography','view3d','motion'].includes(deck[index]?.type)&&effectTimers.length))){render();}if(document.hidden&&memoryTimeout){clearTimeout(memoryTimeout);memoryTimeout=null;render();}if(document.hidden&&startedAt!==null&&!locked){startedAt=null;if($('timer')){$('timer').textContent='Start again';$('timer').classList.remove('running');$('timerhint').textContent='Round reset while away.';}}});
$('daily').addEventListener('click',()=>start('daily'));$('practice').addEventListener('click',()=>start('practice'));['help','rules'].forEach(id=>$(id).addEventListener('click',()=>$('helpdialog').showModal()));['closehelp','gotit'].forEach(id=>$(id).addEventListener('click',()=>$('helpdialog').close()));
document.querySelectorAll('[data-mini]').forEach(btn=>btn.addEventListener('click',()=>{mini=btn.dataset.mini;document.querySelectorAll('[data-mini]').forEach(b=>b.classList.toggle('active',b===btn));start(mode);updateAside();}));
function updateAside(){const copy={mix:['Five puzzles. Five skills.','A different game each round.<br>How sharp is your perception?'],view3d:['Explore every side.','Remember a view.<br>Rotate the shape to match.'],balance:['Find the balance.','One shape. One support.<br>Where does it stay level?'],motion:['Remember the line.','A quick look.<br>Trace it from memory.'],perspective:['See the perspective.','Follow the lines.<br>Find where they meet.'],proportion:['Get a feel for ratios.','One proportion.<br>Stretch a rectangle to match.'],rhythm:['Copy the pulse.','Watch the flashes.<br>Tap the pace. No sound.'],typography:['Get a feel for type.','Size. Weight. Spacing.<br>Recreate what you saw.'],angle:['Find the angle.','One number.<br>A whole dial to explore.'],memory:['Find that colour.','Two seconds to look.<br>A whole wheel to choose from.'],time:['Feel the seconds.','Start. Wait. Stop.<br>No clock until the reveal.']}[mini];$('aside-title').textContent=copy[0];$('aside-copy').innerHTML=copy[1];}
start();updateAside();
